---
- name: Playbook de blockinfile
  hosts: all
  tasks:
   - name: add to hosts
     blockinfile:
       path: /etc/hosts
       block: |
         #Ansible manager
         172.16.2.186

         #Nodo Ansible
         172.16.2.150

       marker: "#{mark} MESSAGE"
